excluded:
 Pods
disabled_rules:
 - cyclomatic_complexity
 - file_length
 - function_body_length
 - line_length
 - statement_position
identifier_name:
 min_length:
  warning: 0
  error: 0
 max_length:
  warning: 60
  error: 100
